[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]
ffi = false # (if true) Caution! It means we are allowing foundry to run commands directly on our machine.

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
